//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KdtTests.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KdtTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {  
        ///   &quot;name&quot;:&quot;Konduto&quot;,
        ///   &quot;address1&quot;:&quot;R. Teodoro Sampaio, 2393&quot;,
        ///   &quot;address2&quot;:&quot;CJ. 111&quot;,
        ///   &quot;zip&quot;:&quot;05406-200&quot;,
        ///   &quot;city&quot;:&quot;Sao Paulo&quot;,
        ///   &quot;state&quot;:&quot;SP&quot;,
        ///   &quot;country&quot;:&quot;BR&quot;
        ///}.
        /// </summary>
        internal static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {  
        ///   &quot;id&quot;:&quot;1&quot;,
        ///   &quot;name&quot;:&quot;Jose da Silva&quot;,
        ///   &quot;email&quot;:&quot;jose.silva@gmail.com&quot;,
        ///   &quot;tax_id&quot;:&quot;01234567890&quot;,
        ///   &quot;phone1&quot;:&quot;11987654321&quot;,
        ///   &quot;phone2&quot;:&quot;1133333333&quot;,
        ///   &quot;vip&quot;:false,
        ///   &quot;new&quot;:false,
        ///   &quot;created_at&quot;:&quot;2014-12-21&quot;,
        ///   &quot;dob&quot;:&quot;1980-12-21&quot;
        ///}.
        /// </summary>
        internal static string customer {
            get {
                return ResourceManager.GetString("customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {
        ///	&quot;user_id&quot;: &quot;405961fab293600daeed93ae561&quot;,
        ///	&quot;fingerprint&quot;: &quot;e4f2c690951038a8f77aa583847&quot;,
        ///	&quot;platform&quot;: &quot;MacIntel&quot;,
        ///	&quot;browser&quot;: &quot;Chrome&quot;,
        ///	&quot;language&quot;: &quot;en_US&quot;,
        ///	&quot;timezone&quot;: &quot;GMT -1&quot;,
        ///	&quot;cookie&quot;: true,
        ///	&quot;javascript&quot;:  true,
        ///	&quot;flash&quot;: true,
        ///	&quot;ip&quot;: &quot;170.149.100.10&quot;
        ///}.
        /// </summary>
        internal static string device {
            get {
                return ResourceManager.GetString("device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {  
        ///	&quot;type&quot;:&quot;flight&quot;,
        ///	&quot;departure&quot;:{  
        ///		&quot;origin_airport&quot;:&quot;GRU&quot;,
        ///		&quot;destination_airport&quot;:&quot;SFO&quot;,
        ///		&quot;date&quot;:&quot;2018-12-25T18:00Z&quot;,
        ///		&quot;number_of_connections&quot;:1,
        ///		&quot;class&quot;:&quot;economy&quot;,
        ///		&quot;fare_basis&quot;:&quot;Y&quot;
        ///	},
        ///	&quot;return&quot;:{  
        ///		&quot;origin_airport&quot;:&quot;SFO&quot;,
        ///		&quot;destination_airport&quot;:&quot;GRU&quot;,
        ///		&quot;date&quot;:&quot;2018-12-30T18:00Z&quot;,
        ///		&quot;number_of_connections&quot;:1,
        ///		&quot;class&quot;:&quot;business&quot;
        ///	},
        ///	&quot;passengers&quot;:[  
        ///		{  
        ///		&quot;name&quot;:&quot;Julia da Silva&quot;,
        ///		&quot;document&quot;:&quot;12345678909&quot;,
        ///		&quot;document_type&quot;:&quot;id&quot;,
        ///		&quot;dob&quot;:&quot;1970-01-01&quot;,
        ///		&quot;nationa [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string flight {
            get {
                return ResourceManager.GetString("flight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {
        ///	&quot;city&quot;:&quot;Sao Paulo&quot;,
        ///	&quot;state&quot;:&quot;SP&quot;,
        ///	&quot;country&quot;:&quot;BR&quot;
        ///}.
        /// </summary>
        internal static string geolocation {
            get {
                return ResourceManager.GetString("geolocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {
        ///	&quot;status&quot;: &quot;ok&quot;,
        ///	&quot;order&quot;: {
        ///		&quot;id&quot;: &quot;1406910391037&quot;,
        ///		&quot;visitor&quot;: &quot;f10e2821bbbea527ea02200352313bc059445190&quot;,
        ///		&quot;timestamp&quot;: 1389047680,
        ///		&quot;score&quot;: 0.75,
        ///		&quot;recommendation&quot;: &quot;review&quot;,
        ///		&quot;status&quot;: &quot;declined&quot;,
        ///		&quot;ip&quot;: &quot;170.149.100.10&quot;,
        ///		&quot;total_amount&quot;:100.00,
        ///		&quot;tax_amount&quot;:3.45,
        ///		&quot;shipping_amount&quot;:20.00,
        ///		&quot;installments&quot;:2,
        ///		&quot;currency&quot;:&quot;USD&quot;,
        ///		&quot;device&quot;: {
        ///			&quot;user_id&quot;: &quot;405961fab293600daeed93ae561&quot;,
        ///		    &quot;fingerprint&quot;: &quot;e4f2c690951038a8f77aa583847&quot;,
        ///		    &quot;platform&quot;: &quot;MacIntel&quot;,
        ///		 [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string konduto_order {
            get {
                return ResourceManager.GetString("konduto_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {
        ///    &quot;status&quot;:&quot;ok&quot;,
        ///    &quot;order&quot;:{
        ///        &quot;id&quot;:&quot;1422044664262&quot;,
        ///        &quot;visitor&quot;:&quot;da39a3ee5e6b4b0d3255bfef95601890afd80709&quot;,
        ///        &quot;score&quot;:-1.0,
        ///        &quot;recommendation&quot;:&quot;NONE&quot;,
        ///        &quot;ip&quot;:&quot;170.149.100.10&quot;
        ///    }
        ///}.
        /// </summary>
        internal static string konduto_order_not_analyzed {
            get {
                return ResourceManager.GetString("konduto_order_not_analyzed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {
        ///	&quot;session_time&quot;: 12,
        ///	&quot;referrer&quot;: &quot;http://www.google.com?q=buy+shirt&quot;,
        ///	&quot;time_site_1d&quot;: 26,
        ///	&quot;new_accounts_1d&quot;: 2,
        ///	&quot;password_resets_1d&quot;: 0,
        ///	&quot;sales_declined_1d&quot;: 1,
        ///	&quot;sessions_1d&quot;: 4,
        ///	&quot;time_site_7d&quot;: 58,
        ///	&quot;time_per_page_7d&quot;: 7,
        ///	&quot;new_accounts_7d&quot;: 9,
        ///	&quot;password_resets_7d&quot;: 3,
        ///	&quot;checkout_count_7d&quot;: 4,
        ///	&quot;sales_declined_7d&quot;: 5,
        ///	&quot;sessions_7d&quot;: 12,
        ///	&quot;time_since_last_sale&quot;: 4
        ///}.
        /// </summary>
        internal static string navigation {
            get {
                return ResourceManager.GetString("navigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {  
        ///	&quot;id&quot;:&quot;1&quot;,
        ///	&quot;visitor&quot;:&quot;a9031kdlas&quot;,
        ///	&quot;timestamp&quot;:123123123123,
        ///	&quot;total_amount&quot;:120.5,
        ///	&quot;shipping_amount&quot;:5.0,
        ///	&quot;tax_amount&quot;:3.0,
        ///	&quot;currency&quot;:&quot;USD&quot;,
        ///	&quot;installments&quot;:1,
        ///	&quot;ip&quot;:&quot;192.168.0.1&quot;,
        ///    &quot;customer&quot;:{
        ///		&quot;id&quot;:&quot;1&quot;,
        ///        &quot;name&quot;:&quot;Jose da Silva&quot;,
        ///        &quot;email&quot;:&quot;jose.silva@gmail.com&quot;,
        ///        &quot;tax_id&quot;:&quot;01234567890&quot;,
        ///        &quot;phone1&quot;:&quot;11987654321&quot;,
        ///        &quot;phone2&quot;:&quot;1133333333&quot;,
        ///        &quot;vip&quot;:false,
        ///        &quot;new&quot;:false,
        ///		&quot;created_at&quot;:&quot;2014-12-21&quot;,
        ///		&quot;dob&quot;:&quot;1980-12-21&quot;
        ///	},
        ///	&quot;reco [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string order {
            get {
                return ResourceManager.GetString("order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {
        ///  &quot;name&quot;: &quot;Carlos Siqueira&quot;,
        ///  &quot;document&quot;: &quot;XYZ1234&quot;,
        ///  &quot;document_type&quot;: &quot;passport&quot;,
        ///  &quot;dob&quot;: &quot;1970-12-01&quot;,
        ///  &quot;nationality&quot;: &quot;US&quot;,
        ///  &quot;frequent_traveler&quot;: false,
        ///  &quot;special_needs&quot;: true,
        ///  &quot;loyalty&quot;: {
        ///    &quot;program&quot;: &quot;multiplus&quot;,
        ///    &quot;category&quot;: &quot;silver&quot;
        ///  }
        ///}.
        /// </summary>
        internal static string passenger {
            get {
                return ResourceManager.GetString("passenger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a [
        ///	{
        ///	   &quot;bin&quot;:&quot;1234&quot;,
        ///	   &quot;last4&quot;:&quot;1234&quot;,
        ///	   &quot;expiration_date&quot;:&quot;010214&quot;,
        ///	   &quot;status&quot;:&quot;approved&quot;,
        ///	   &quot;type&quot;:&quot;credit&quot;
        ///	},
        ///	{
        ///		&quot;type&quot;: &quot;debit&quot;
        ///	},
        ///	{
        ///		&quot;type&quot;: &quot;voucher&quot;
        ///	},
        ///	{
        ///		&quot;type&quot;: &quot;transfer&quot;
        ///	},
        ///	{
        ///		&quot;expiration_date&quot;:&quot;2015-01-01&quot;,
        ///		&quot;type&quot;: &quot;boleto&quot;
        ///	}
        ///].
        /// </summary>
        internal static string payments {
            get {
                return ResourceManager.GetString("payments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {
        ///    &quot;id&quot;:&quot;Seller Id&quot;,
        ///    &quot;name&quot;:&quot;Sellerio Name&quot;,
        ///    &quot;created_at&quot;:&quot;2014-12-08&quot;
        ///}.
        /// </summary>
        internal static string seller {
            get {
                return ResourceManager.GetString("seller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a [
        ///    {
        ///      &quot;sku&quot;: &quot;9919023&quot;,
        ///      &quot;category&quot;: 201,
        ///      &quot;name&quot;: &quot;Green T-Shirt&quot;,
        ///      &quot;description&quot;: &quot;Male Green T-Shirt V Neck&quot;,
        ///	  &quot;product_code&quot;: &quot;123456789999&quot;,
        ///      &quot;unit_cost&quot;: 1999.99,
        ///      &quot;quantity&quot;: 1.0,
        ///	  &quot;created_at&quot;: &quot;2014-12-21&quot;
        ///    },
        ///    {
        ///      &quot;sku&quot;: &quot;0017273&quot;,
        ///      &quot;category&quot;: 202,
        ///      &quot;name&quot;: &quot;Yellow Socks&quot;,
        ///      &quot;description&quot;: &quot;Pair of Yellow Socks&quot;,
        ///      &quot;unit_cost&quot;: 29.90,
        ///      &quot;quantity&quot;: 2.0,
        ///      &quot;discount&quot;: 5.00
        ///    }
        ///].
        /// </summary>
        internal static string shopping_cart {
            get {
                return ResourceManager.GetString("shopping_cart", resourceCulture);
            }
        }
    }
}
